export const AllItemsData = [
    {
        id: 1,
        image: "/cards/bg5.jpeg",
        for: "Sotiladi",
        name: "Yangi choshtepa uylari",
        price: "53 000",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 2,
        image: "/cards/bg2.jpeg",
        for: "Dam olish",
        name: "Yangi choshtepa uylari",
        price: "249",
        time: "24 soat",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 3,
        image: "/cards/bg3.jpeg",
        for: "Ijaraga",
        name: "Yangi choshtepa uylari",
        price: "400",
        time: "1 oy",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 4,
        image: "/cards/bg4.jpeg",
        for: "Sotiladi",
        name: "Yangi choshtepa uylari",
        price: "53 000",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 5,
        image: "/cards/bg5.jpeg",
        for: "Dam olish",
        name: "Yangi choshtepa uylari",
        price: "249",
        time: "24 soat",
        type: "Hovli",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 6,
        image: "/cards/bg6.jpeg",
        for: "Ijaraga",
        name: "Yangi choshtepa uylari",
        price: "400",
        time: "1oy",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 7,
        image: "/cards/bg7.jpeg",
        for: "Sotiladi",
        name: "Yangi choshtepa uylari",
        price: "53 000",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 8,
        image: "/cards/bg8.jpeg",
        for: "Dam olish",
        name: "Yangi choshtepa uylari",
        price: "249",
        time: "24 soat",
        type: "Hovli",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 9,
        image: "/cards/bg3.jpeg",
        for: "Ijaraga",
        name: "Yangi choshtepa uylari",
        price: "400",
        time: "1 oy",
        type: "Hovli",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 10,
        image: "/cards/room.jpeg",
        for: "Sotiladi",
        name: "Yangi Xonsaroy uylari",
        price: "53 000",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Xonsaroy , 46 -uy"
    },
    {
        id: 11,
        image: "/cards/bg2.jpeg",
        for: "Dam olish",
        name: "Yangi choshtepa uylari",
        price: "249",
        time: "24 soat",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 12,
        image: "/cards/bg3.jpeg",
        for: "Ijaraga",
        name: "Yangi Oqtepa uylari",
        price: "400",
        time: "1 oy",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Oqtepa , 46 -uy"
    },
    {
        id: 13,
        image: "/cards/bg4.jpeg",
        for: "Sotiladi",
        name: "Piramit uylari",
        price: "53 000",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Piramit, 46 -uy"
    },
    {
        id: 14,
        image: "/cards/bg5.jpeg",
        for: "Dam olish",
        name: "Yangi choshtepa uylari",
        price: "249",
        time: "24 soat",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Xonsaroy , 46 -uy"
    },
    {
        id: 15,
        image: "/cards/bg6.jpeg",
        for: "Ijaraga",
        name: "Xonsaroy uylari",
        price: "400",
        time: "1oy",
        type: "Hovli",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Xonsaroy , 46 -uy"
    },
    {
        id: 16,
        image: "/cards/bg7.jpeg",
        for: "Sotiladi",
        name: "Oqtepa uylari",
        price: "53 000",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
    {
        id: 17,
        image: "/cards/bg8.jpeg",
        for: "Dam olish",
        name: "Piramit uylari",
        price: "249",
        time: "24 soat",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Piramit, 46 -uy"
    },
    {
        id: 18,
        image: "/cards/bg3.jpeg",
        for: "Ijaraga",
        name: "Oqtepa uylari",
        price: "400",
        time: "1 oy",
        type: "Ofis",
        size: "56 m",
        many: "2 xonali",
        floor: "2 / 7 qavat",
        location: "Tashkent, Yangi Choshtepa , 46 -uy"
    },
]